from django.conf import settings

USER_SETTINGS = getattr(settings, "EXPENSES", {})

EXPENSES = {
    "CURRENCY": USER_SETTINGS.get("CURRENCY", "XOF"),
    "CURRENCY_SYMBOL": USER_SETTINGS.get("CURRENCY_SYMBOL", "CFA"),
    "DECIMAL_PLACES": USER_SETTINGS.get("DECIMAL_PLACES", 0),
    "AUTO_REFERENCE_PREFIX": USER_SETTINGS.get("AUTO_REFERENCE_PREFIX", "DEP"),
    "REQUIRE_APPROVAL": USER_SETTINGS.get("REQUIRE_APPROVAL", True),
    "MAX_ATTACHMENTS": USER_SETTINGS.get("MAX_ATTACHMENTS", 5),
    "ALLOWED_ATTACHMENT_TYPES": USER_SETTINGS.get(
        "ALLOWED_ATTACHMENT_TYPES", ["pdf", "jpg", "jpeg", "png"]
    ),
    "ENABLE_COMMENTS": USER_SETTINGS.get("ENABLE_COMMENTS", True),
    "ENABLE_WORKFLOW": USER_SETTINGS.get("ENABLE_WORKFLOW", True),
    "ACCOUNT_CODE_PREFIX": USER_SETTINGS.get("ACCOUNT_CODE_PREFIX", ""),
    "ALLOW_PARTIAL_PAYMENTS": USER_SETTINGS.get("ALLOW_PARTIAL_PAYMENTS", True),
    "REQUIRE_ACCOUNT_REFERENCE": USER_SETTINGS.get("REQUIRE_ACCOUNT_REFERENCE", False),
    "ENFORCE_BUDGET": USER_SETTINGS.get("ENFORCE_BUDGET", True),
    "ENABLE_MULTI_ENTREPRISE": USER_SETTINGS.get("ENABLE_MULTI_ENTREPRISE", False),
    "ENTREPRISE_RESOLVER": USER_SETTINGS.get("ENTREPRISE_RESOLVER"),
    "ALLOW_GLOBAL_CATEGORIES": USER_SETTINGS.get("ALLOW_GLOBAL_CATEGORIES", True),
    "MULTI_ENTREPRISE_SUPERUSER_GLOBAL": USER_SETTINGS.get(
        "MULTI_ENTREPRISE_SUPERUSER_GLOBAL", False
    ),
}
