# Generated by Django 5.2.11 on 2026-07-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='depreciation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual depreciation rate percentage (for fixed assets)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='requires_approval',
            field=models.BooleanField(default=True, help_text='Whether this expense type requires approval'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='requires_receipt',
            field=models.BooleanField(default=True, help_text='Whether a receipt/justificatif is required'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='requires_vendor',
            field=models.BooleanField(default=True, help_text='Whether a vendor/tiers is required'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='unit',
            field=models.CharField(blank=True, help_text='Default unit of measure (kg, litre, pièce...)', max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_nature',
            field=models.CharField(blank=True, choices=[('achat', 'Achats'), ('fonctionnement', 'Frais de fonctionnement'), ('personnel', 'Personnel'), ('marketing', 'Marketing et publicité'), ('investissement', 'Investissements'), ('impots', 'Impôts et taxes'), ('divers', 'Divers')], help_text='Nature: operating, investment, mission, purchase...', max_length=20),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='default_account_code',
            field=models.CharField(blank=True, help_text='OHADA account code (e.g. 6251 for fuel)', max_length=20),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='default_vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default VAT rate percentage (e.g. 18.00)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='expense_nature',
            field=models.CharField(blank=True, choices=[('achat', 'Achats'), ('fonctionnement', 'Frais de fonctionnement'), ('personnel', 'Personnel'), ('marketing', 'Marketing et publicité'), ('investissement', 'Investissements'), ('impots', 'Impôts et taxes'), ('divers', 'Divers')], help_text='Type of expense: ACHAT, FONCTIONNEMENT, PERSONNEL...', max_length=20),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon class (e.g. fa-gas-pump)', max_length=50),
        ),
    ]
